# -*- coding: utf-8 -*-
"""bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tExKsjuWWGabYmtXobHJjdU3u2qFkFJt
"""

# Exemplo de Clasificador Bayesiano para Iris Dataset
# Fazer o Experimento para Digits Dataset 

from sklearn import datasets  
import matplotlib.pyplot as plt  
import pandas as pd  

# Bibliotecas para amostragem e Modelo Bayesiano
from sklearn.model_selection import train_test_split  
from sklearn.naive_bayes import GaussianNB

# Obtendo o conjunto de dados da Iris (150 exemplos de 4 atributos e 3 classes)
iris = datasets.load_iris()  
class_names = iris.target_names  
iris_df=pd.DataFrame(iris.data, columns=iris.feature_names)  
iris_df['target']=iris.target

iris_df.head()
iris_df.describe()

X_train, X_test, y_train, y_test = train_test_split(iris_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']], iris_df['target'], random_state=0)
nb = GaussianNB()  
nb.fit(X_train, y_train)   
y_predict = nb.predict(X_test)  
print("Precisão NB: {:.2f}".format(nb.score(X_test, y_test)))